#!/bin/sh
#
# Report any outstanding binary patches as determined by syspatch(8).
# Output goes to to stdout; available patches also logged to syslog.

set -e

export PATH=/bin:/usr/bin:/usr/sbin

CMD=$(basename $0)

set -A PATCHES $(syspatch -c)
num=${#PATCHES[*]}

if [ $num -gt 0 ]; then
	case $num in
		1)  suf="" ;;
		*)  suf="es" ;;
	esac
	msg="$num available patch${suf}: ${PATCHES[*]}"
	echo "${msg}"
	echo "${msg}" | logger -t "${CMD}"
else
	echo "None."
fi
