#!/bin/sh
#
# Report any outstanding binary patches as determined by syspatch(8).
# Output goes to syslog and to standard output.

set -e

export PATH=/bin:/usr/bin:/usr/sbin


CMD=$(basename $0)

set -A PATCHES $(syspatch -c)
num=${#PATCHES[*]}

if [ $num -gt 0 ]; then
	msg="$num available patches: ${PATCHES[*]}"
	echo "${msg}"
	echo "${msg}" | logger -t "${CMD}"
fi
